spring:
  datasource:
    url: jdbc:mysql://localhost:3306/card-verification?userSSL=false&serverTimezone=UTC
    username: verifier
    password: verifier
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
